-- Author      : ChimoB
-- Create Date : 03/01/2025 12:00:17
 
 -- si pongo la viarible local, se ha de usar la funcion globals, si no se puede acceder de forma directa
 
-- global --
local CONSTANT = {}
 -- global --
    -- GUI --
CONSTANT.GUI = {}
CONSTANT.GUI.BUTTON_HEIGHT = 30
CONSTANT.GUI.BUTTON_PADDING = 5
CONSTANT.GUI.LEFT_PADDING = 30
CONSTANT.GUI.TEXT_WIDTH = 50
CONSTANT.GUI.TOPLEFT = "TOPLEFT"
CONSTANT.GUI.LEFT = "LEFT"
CONSTANT.GUI.ANCHOR_RIGHT = "ANCHOR_RIGHT"

  -- Events --
CONSTANT.EVENT = {}
CONSTANT.EVENT.GROUP_ROSTER_UPDATE = "GROUP_ROSTER_UPDATE"
CONSTANT.EVENT.LOOT_OPENED = "LOOT_OPENED"
CONSTANT.EVENT.PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD"
CONSTANT.EVENT.ZONE_CHANGED_NEW_AREA = "ZONE_CHANGED_NEW_AREA"
CONSTANT.EVENT.PLAYER_LOGIN = "PLAYER_LOGIN"
CONSTANT.EVENT.PARTY_LEADER_CHANGED = "PARTY_LEADER_CHANGED"
CONSTANT.EVENT.ANCHOR_RIGHT = "ANCHOR_RIGHT"

     -- Command --
CONSTANT.COMMAND = {}
CONSTANT.COMMAND.SHOW = "Show"
CONSTANT.COMMAND.HIDE = "Hide"
CONSTANT.COMMAND.HELP = "Help"
 
    -- Item --
CONSTANT.ITEM = {}
CONSTANT.ITEM.WEAPON = "Weapon"
CONSTANT.ITEM.ARMOR = "Armor"
CONSTANT.ITEM.TRINKET = "Trinket"
CONSTANT.ITEM.MAX_QUALITY = 3       -- CAMBIAR A 4

-- Return the constants table to other files
-- Globals and not Constants because the function Constants throws error
function Globals()
   return CONSTANT
end